# Generated by Django 5.1 on 2024-08-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiatouragency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
